#!/usr/bin/env bash
# Creates /var/run/myscript.pid containing its PID and handles signals

PID_FILE="/var/run/myscript.pid"
echo $$ | sudo tee "$PID_FILE" > /dev/null

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$PID_FILE"; exit' SIGQUIT SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

