#!/usr/bin/env bash
#fa
echo $$ > /var/run/myscript.pid
sigterm_handler() {
    echo "I hate the kill command"
    # Faylı sil və skripti dayandır
    rm -f "$PID_FILE"
    exit 0
}

sigint_handler() {
    echo "Y U no love me?!"
}

sigquit_handler() {
    # Faylı sil və skripti dayandır
    rm -f "$PID_FILE"
    exit 0
}

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 1
done
